### ISSUE TITLE
Demo page VM can be escaped

### ISSUE THREAD

**Issue by ivanvanderbyl** [ebidel/try-puppeteer#12]
Because the demo page uses Node's "vm" package, the context essentially inherits from Object, which inherits from Function, which means we can escape the context and do malicious things (sorry about that):

Running:
```js
new Function(`this.constructor.constructor('return process')().exit()`)
```

Will kill node.

There's more discussion about that here https://github.com/gf3/sandbox/issues/50

I'd recommend switching it out for "vm2", which is more secure and has a similar API.

**Comment by ebidel** [comment]
Not too worried about the security of the demo/machine. It's meant as a demo/testing util.

Running that doesn't seem to have an effect for me. What exactly will repro this?

**Comment by ivanvanderbyl** [comment]
Fair enough, I figured it's probably inside a container anyway.

That example just returns a wrapped exit function, if you call it, you should see a 503 next.

```
new Function(`this.constructor.constructor('return process')().exit()`)()
```

**Comment by ebidel** [comment]
Yea you're right. Kills it. Thanks for the tips. Would you be interested in sending a PR with the vm2 update?

**Comment by ebidel** [comment]
Deployed `vm2`!
