### ISSUE TITLE
try-puppeteer demo site is down?

### ISSUE THREAD

**Issue by shahardanos** [ebidel/try-puppeteer#13]
Hi,
 It seems that the live demo website has stopped working.
Steps to reproduce:

1. Navigate to https://try-puppeteer.appspot.com/
2. Hit 'Run It' (to run the screenshot.js example).
3. Fetching takes a lot of time, resulting in: 'TypeError: Failed to fetch'. The request to https://backend-dot-try-puppeteer.appspot.com/run is failed as 502 showing: 502 Bad Gateway
nginx

Are you award to this issue? 
Can this be fixed?

Thanks!

**Comment by ebidel** [comment]
Should be back now.

**Comment by shahardanos** [comment]
Still seems to be down :(
Tried to run more than one example (screenshot, pdf, etc), all are resulted with 500 error code saying:
"Error running your code. Error: Navigation Timeout Exceeded: 30000ms exceeded"

**Comment by ebidel** [comment]
How about now?

**Comment by shahardanos** [comment]
Only the 'screenshot.js' does not fail. All the other just do not work, resulting in "Error running your code. Error: Navigation Timeout Exceeded: 30000ms exceeded"
Also, when I tried to changed the 'example.com' URL in 'screenshot.js', it resulted in the same above-mentioned error.
Sorry for being this nuisance 😮
