### ISSUE TITLE
Using puppeteer.connect(options)

### ISSUE THREAD

**Issue by rpascal** [ebidel/try-puppeteer#16]
Would it be possible to use this to connect using puppeteer.connect(options)? It would be nice to be able to connect to Chromium instance running in docker.

**Comment by ebidel** [comment]
What do you mean exactly? You want to connect to this app's chromium from another app? That's not possible.

**Comment by rpascal** [comment]
No, something like what https://www.browserless.io/ is doing. 

```
puppeteer.connect({
  browserWSEndpoint: 'wss://chrome.browserless.io'
}).then(async browser => {
  const page = await browser.newPage();
  await page.goto('https://example.com');
  await page.screenshot({path: 'screenshot.png'});
  page.close();
});
```
So the endpoint would be without a Docker container separate from the actual application itself.

**Comment by ebidel** [comment]
Oh gotcha. That might be interesting but I don't want to get in the
business of running a web service for this. It's meant just as a quick and
dirty playground to try code snippets.

**Comment by rpascal** [comment]
Fair enough, I'm sure I can figure it out with the provided resources. Thank you!
