### ISSUE TITLE
Docker build apt-utils warning

### ISSUE THREAD

**Issue by robertjchristian** [ebidel/try-puppeteer#18]
debconf: delaying package configuration, since apt-utils is not installed

**Comment by robertjchristian** [comment]
It's relatively benign as far as I can tell, but shows up red during app
depoly...

DEBUG: Reading GCS logfile: 206 (read 118 bytes)

debconf: delaying package configuration, since apt-utils is not installed

Fetched 97.1 MB in 12s (7904 kB/s)

If it's not needed, should consider RUN apt-get update && apt-get install
-y --no-install-recommends apt-utils.  Prob not a biggy, just thought I
would report it.  Also wondering whether Ubuntu would be a little more
robust running in docker as opposed to node-slim?

**Comment by ebidel** [comment]
Ubuntu creates a much bigger image: https://github.com/ebidel/try-puppeteer/commit/cfe40c94c6e44fe9dba7d3f3ee47728b1e62a518
