### ISSUE TITLE
Error: Protocol error (Page.enable): Target closed.

### ISSUE THREAD

**Issue by HapLifeMan** [ebidel/try-puppeteer#20]
Hey, you have an error when running the basic script on your website, it returns:

```
Error running your code. Error: Protocol error (Page.enable): Target closed.
```

Do you know how to fix this?

**Comment by ebidel** [comment]
should be back now.

**Comment by JakeChampion** [comment]
I'm seeing this error again on https://try-puppeteer.appspot.com/

**Comment by ebidel** [comment]
Restarted the vm
