### ISSUE TITLE
Debugging the website locally

### ISSUE THREAD

**Issue by mattduffield** [ebidel/try-puppeteer#28]
First of all, this is a great demo! I am curious what are the steps to debug the website using localhost? Also, do you have to use `yarn restart` to get any of your coding changes to be applied? It seems like a very slow workflow so I wanted to be sure this was the correct approach. If there is any other documentation on authoring/debugging this, I would greatly appreciate it.

**Comment by ebidel** [comment]
Correct, you'll have to use `yarn restart` to rebuild the Docker container.

However, it's easier to run the frontend server and backend server locally:

Start frontend server:

```
yarn serve
```

Start backend server:

```
cd backend
yarn serve
```

Although you'll still need to restart the backend if you make any changes to `backend/server.js`.
