### ISSUE TITLE
Error running your code. Error: Failed to launch chrome!

### ISSUE THREAD

**Issue by nuthinking** [ebidel/try-puppeteer#29]
Perhaps something got broken?

**Comment by ebidel** [comment]
Can you provide more info. I'm not seeing any issues atm.

**Comment by chuckwatson87** [comment]
Hello, I am getting this as well with the following output:

(node:27) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!
[0801/204111.439393:FATAL:zygote_host_impl_linux.cc(116)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
#0 0x564ce50f179c base::debug::StackTrace::StackTrace()
#1 0x564ce50711c0 logging::LogMessage::~LogMessage()
#2 0x564ce6491830 service_manager::ZygoteHostImpl::Init()
#3 0x564ce4d6365e content::ContentMainRunnerImpl::Initialize()
#4 0x564ce4d97b08 service_manager::Main()
#5 0x564ce4d61be1 content::ContentMain()
#6 0x564ce915dd8d headless::(anonymous namespace)::RunContentMain()
#7 0x564ce915de18 headless::HeadlessBrowserMain()
#8 0x564ce4d9521a headless::HeadlessShellMain()
#9 0x564ce32141ac ChromeMain
#10 0x7fc49dc00b45 __libc_start_main
#11 0x564ce321402a _start

Received signal 6
#0 0x564ce50f179c base::debug::StackTrace::StackTrace()
#1 0x564ce50f1301 base::debug::(anonymous namespace)::StackDumpSignalHandler()
#2 0x7fc4a3a7c890 <unknown>
#3 0x7fc49dc14067 gsignal
#4 0x7fc49dc15448 abort
#5 0x564ce50f0155 base::debug::BreakDebugger()
#6 0x564ce5071629 logging::LogMessage::~LogMessage()
#7 0x564ce6491830 service_manager::ZygoteHostImpl::Init()
#8 0x564ce4d6365e content::ContentMainRunnerImpl::Initialize()
#9 0x564ce4d97b08 service_manager::Main()
#10 0x564ce4d61be1 content::ContentMain()
#11 0x564ce915dd8d headless::(anonymous namespace)::RunContentMain()
#12 0x564ce915de18 headless::HeadlessBrowserMain()
#13 0x564ce4d9521a headless::HeadlessShellMain()
#14 0x564ce32141ac ChromeMain
#15 0x7fc49dc00b45 __libc_start_main
#16 0x564ce321402a _start
  r8: 00007fc4a4081a00  r9: 00001a91a5744000 r10: 0000000000000008 r11: 0000000000000202
 r12: 00007ffd14c07f18 r13: 0000000000000161 r14: 00007ffd14c07f20 r15: 00007ffd14c07f28
  di: 0000000000000025  si: 0000000000000025  bp: 00007ffd14c07a60  bx: 00007ffd14c07ad0
  dx: 0000000000000006  ax: 0000000000000000  cx: 00007fc49dc14067  sp: 00007ffd14c07928
  ip: 00007fc49dc14067 efl: 0000000000000202 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.
