### ISSUE TITLE
Missing fonts

### ISSUE THREAD

**Issue by stucker71** [ebidel/try-puppeteer#30]
I've managed to setup puppeteer with GAE and got it working. However, there are missing fonts - for example where html font family states Georgia, Tahoma, Trebuchet MS, and Verdana these are missing and conversion to PDF will default to Times New Roman. Fonts Times New Roman, Arial, and Courier New all work fine.

Any ideas on how to get the missing fonts installed and working with Puppeteer on GAE?

Thanks.

**Comment by ebidel** [comment]
GAE flex or standard? For Standard/Docker, you'll have to install the fonts you need: https://github.com/ebidel/try-puppeteer/blob/master/backend/Dockerfile#L33

**Comment by stucker71** [comment]
Thanks, I'm using GAE flex, Can you point me in the right direction? I'm new to this stuff! Thanks.

**Comment by ebidel** [comment]
The link I shared above shows how to install missing fonts. You'll need to either use that Dockerfile and/or lookup the ubuntu font packages to install and include them in your `apt-get install` command

**Comment by stucker71** [comment]
Many thanks, much appreciated

**Comment by stucker71** [comment]
Just read GAE standard (Node environment) now supports Puppeteer. Is it possible to install the package ttf-mscorefonts-installer (Microsoft core fonts for the web) on GAE standard? These are widely used and common web safe fonts.
