### ISSUE TITLE
upgrading node and puppeteer 

### ISSUE THREAD

**Issue by sahanatroam** [ebidel/try-puppeteer#33]
@ebidel any plans to upgrade the node version to node10 and pup to 1.6.0>

**Comment by ebidel** [comment]
I guess eventually. Why do you ask?

**Comment by ebidel** [comment]
Updated the site to pptr 1.7.0

**Comment by sahanatroam** [comment]
Because I have this issue with www.watervare.co.nz website. If you try to load the website it might not work

**Comment by sahanatroam** [comment]
Node10 because that's the latest supported version. No other major reason

**Comment by sahanatroam** [comment]
@ebidel did you update the pptr version that gets installed too ?
https://github.com/ebidel/try-puppeteer/commit/e3cd2911fc198525e68be404f113ade66b658906
I do not see that commit

**Comment by sahanatroam** [comment]
@ebidel I just tried on pptr 1.7 and http://www.watercare.co.nz/ seems to be not working
```
Error running your code. Error: net::ERR_CERT_AUTHORITY_INVALID at http://www.watercare.co.nz/
```
