### ISSUE TITLE
Shareable link

### ISSUE THREAD

**Issue by lusarz** [ebidel/try-puppeteer#35]
Is it possible to generate shareable link from `https://try-puppeteer.appspot.com/` ? 

It may be useful to show issue reproduction in puppeteer repository. For example in cases like here:
https://github.com/GoogleChrome/puppeteer/issues/3299#issuecomment-424456924

**Comment by ebidel** [comment]
Dupe of https://github.com/ebidel/try-puppeteer/issues/10
