### ISSUE TITLE
Broken flexbox layout in Firefox/Edge

### ISSUE THREAD

**Issue by digitarald** [ebidel/try-puppeteer#36]
STR: Run the default example

AR:
- Result panel stays fixed and doesn't resize to 50%
- Header offset on the right is misaligned.

Chrome Canary | Firefox Nightly

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/8599/46833487-9f1e0f00-cd5d-11e8-9eb5-647dde595e89.png">

Analysis (thanks to @dholbert):

The overall height of elements in `.puppeteer-results` make it larger than the viewport height. The layout is optimizing for a Chrome bug that is being fixed: https://bugs.chromium.org/p/chromium/issues/detail?id=596743

Solution:

Adding `min-height: 0` to `.puppeteer-results` fixes the issue.

![image](https://user-images.githubusercontent.com/8599/46834369-1a80c000-cd60-11e8-8f9e-cbdcf7cb0042.png)

**Comment by ebidel** [comment]
Interested in a pr?

**Comment by digitarald** [comment]
Chrome landed flexbox patch. Canary now has the broken layout as well.

<img width="961" alt="image" src="https://user-images.githubusercontent.com/8599/47740626-78a11480-dc35-11e8-8054-2dea7d4514fb.png">

> Interested in a pr?

Yes, but time is an issue so I would not block on me.
