### ISSUE TITLE
search.js not working on https://try-puppeteer.appspot.com/

### ISSUE THREAD

**Issue by shilongfoo** [ebidel/try-puppeteer#48]
Steps to reproduce

Tell us about your environment:

    Puppeteer version: v1.9.0
    Platform / OS version: Windows 10/latest chrome/latest firefox as of today
    URLs (if applicable): https://try-puppeteer.appspot.com/
    Node.js version: nil

What steps will reproduce the problem?

    Go to https://try-puppeteer.appspot.com/
    Select search.js from examples selection
    Hit Run

Please include code that reproduces the issue.

    No code needed. Just try search example.

What is the expected result?
Extract the results from the page.

What happens instead?
Error running your code. Error: No node found for selector: #searchbox input

**Comment by thomaschaplin** [comment]
@shilongfoo this will be fixed by https://github.com/puppeteer/puppeteer/pull/6471

@ebidel please feel free to close this issue as my above PR will resolve it.
