### ISSUE TITLE
PSA: Taking down try-puppeteer.appspot.com

### ISSUE THREAD

**Issue by paulirish** [ebidel/try-puppeteer#59]
Hi folks, we're taking down https://try-puppeteer.appspot.com/ as it's running a quite old version of puppeteer and it's not being maintained.

Of course, this try-puppeteer open source project is still here, which allows anyone to put up their own version. But the public instance will be offline.

Apologies and thanks for understanding.

**Comment by theDavidBarton** [comment]
hi @paulirish, 
it sounds cool! my PR about [putting a warning about its version](https://github.com/puppeteer/puppeteer/pull/7639) in Puppeteer README.md will be obsolete then.

will there be a new try-puppeteer project which will be maintained by the Puppeteer community? if there will be: I'd be glad to contribute to 👍
