### ISSUE TITLE
Demo page security

### ISSUE THREAD

**Issue by kimmobrunfeldt** [ebidel/try-puppeteer#6]
Hi!

Thanks for the great demo page. I just built https://github.com/alvarcarto/url-to-pdf-api which uses Puppeteer to produce PDFs. Someone noticed that our API also allows to reveal file contents in the server when setting e.g. `file:///etc/hosts` as the URL.

You might know this already but I noticed the same is possible with https://try-puppeteer.appspot.com/ demo page. You can reveal files with `await page.goto('file:///etc/hosts');`

**Comment by ebidel** [comment]
Thanks for the heads up! Chrome requires flags to allow access to `file:///` from various web platform APIs. Puppeeteer might want to do the same for security reasons.

In the meantime, I think we can intercept requests and prevent navigations to anything but `https?://` urls.

**Comment by anvaka** [comment]
Looks like it is still possible to get list of all your users.

If you run this code -

``` js
const browser = await puppeteer.launch();

const page = await browser.newPage();
await page.goto('file:///etc/passwd');

console.log(await page.content());
await page.screenshot({path: 'screenshot.png'});

await browser.close();
```

You'll get all users on the host.

**Comment by Janpot** [comment]
@ebidel Looks like I'm also able to render pages on private IPs

```js
const browser = await puppeteer.launch();

const page = await browser.newPage();
await page.goto('http://127.0.0.1:8080');

console.log(await page.content());
await page.screenshot({path: 'screenshot.png'});

await browser.close();
```

![screen shot 2018-02-14 at 12 16 27](https://user-images.githubusercontent.com/2109932/36201709-25105846-1181-11e8-9d49-d817f8dd523a.png)

**Comment by ebidel** [comment]
That's the https://backend-dot-try-puppeteer.appspot.com/ container. The app runs on the same vm and exposes `8080` as a webservice.

**Comment by Janpot** [comment]
Well sure, I put that as quick example. One could imagine someone using the try-puppeteer code editor to scan the private IP address space looking for sensitive data.

**Comment by st22** [comment]
@ebidel 
I think you already know, we still can use "file:" scheme by below patterns.

1. upper characters
　→　 'FILE://etc/passwd'
2. cantaining unintended「.」
　→　'file:/./etc/passwd'
3. string concatenation
　→　'fi'+'le://etc/passwd'

thank you.

**Comment by nachobonilla** [comment]
@ebidel can you provide a security contact email ? It would be great to send an email with more information on a variant of this issue that could have higher risks than the one provided here (and that should be fixed asap).

**Comment by ebidel** [comment]
This is not an official project so no security email.
