### ISSUE TITLE
https://try-puppeteer.appspot.com -> not working ( Error 404 )

### ISSUE THREAD

**Issue by AnasQiblawi** [ebidel/try-puppeteer#65]
your website stoped working
[https://try-puppeteer.appspot.com](https://try-puppeteer.appspot.com)

it shows this:
>404. That’s an error.
>The requested URL was not found on this server. That’s all we know.

**Comment by SrGeneroso** [comment]
I wanted to try it.

**Comment by ebidel** [comment]
I think the GCP project has been taken down. Unfortunately I no longer have access to that project.
