### ISSUE TITLE
Block-images.js does not work

### ISSUE THREAD

**Issue by hamadr** [ebidel/try-puppeteer#7]
![image](https://user-images.githubusercontent.com/1525665/32097571-42d73566-bb0a-11e7-83d3-0b62d4370210.png)

Logs print ```Error running your code. Error: SSL Certificate error: ERR_CERT_AUTHORITY_INVALID```

**Comment by ebidel** [comment]
See https://github.com/GoogleChrome/puppeteer/pull/1192
